name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Firebase
        run: npx firebase-tools@latest deploy --only hosting --project prakongshop-fb71b --token "${{ secrets.FIREBASE_TOKEN }}"
